export enum Categories{
    'Arts and Music',
    'Biographies',
    'Business',
    'Comics',
    'Computers and Tech',
    'Cooking',
    'Education and Reference',
    'Entertainment',
    'Health and Fitness',
    'History',
    'Hobbies and Crafts',
    'Home and Garden',
    'Kids',
    'Medical',
    'Literature and Fiction',
    'Mysteries',
    'Romance',
    'Sci-Fi',
    'Science and Math',
    'Travel',
    'True Crime',
    'Sports',
    'Teen'
}